site_name: Colorer Library
site_url: https://colorer.github.io/

nav:
  - Home: index.md
  - Getting started:
    - Schemes library: catalog-base.md
  - Advanced usage:
    - Catalog.xml: catalog-xml.md
    - Type of paths: file-paths.md

theme:
  name: material
  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - pymdownx.details
